# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaffoldmeshfitterwidget.ui'
#
# Created: Mon Jul 15 11:06:00 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScaffoldfitterWidget(object):
    def setupUi(self, ScaffoldfitterWidget, shared_open_gl_widget):
        ScaffoldfitterWidget.setObjectName("ScaffoldfitterWidget")
        ScaffoldfitterWidget.resize(1957, 998)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScaffoldfitterWidget.sizePolicy().hasHeightForWidth())
        ScaffoldfitterWidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(ScaffoldfitterWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(ScaffoldfitterWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(410, 135))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 408, 956))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.fitPage = QtGui.QWidget()
        self.fitPage.setGeometry(QtCore.QRect(0, 0, 387, 931))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitPage.sizePolicy().hasHeightForWidth())
        self.fitPage.setSizePolicy(sizePolicy)
        self.fitPage.setObjectName("fitPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.fitPage)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.transformation_groupBox = QtGui.QGroupBox(self.fitPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.transformation_groupBox.setFont(font)
        self.transformation_groupBox.setObjectName("transformation_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.transformation_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pitch_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pitch_label.setFont(font)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout_4.addWidget(self.pitch_label, 5, 2, 1, 1)
        self.yaw_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.yaw_doubleSpinBox.setFont(font)
        self.yaw_doubleSpinBox.setMinimum(-360.0)
        self.yaw_doubleSpinBox.setMaximum(360.0)
        self.yaw_doubleSpinBox.setObjectName("yaw_doubleSpinBox")
        self.gridLayout_4.addWidget(self.yaw_doubleSpinBox, 6, 0, 1, 1)
        self.roll_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.roll_doubleSpinBox.setFont(font)
        self.roll_doubleSpinBox.setMinimum(-360.0)
        self.roll_doubleSpinBox.setMaximum(360.0)
        self.roll_doubleSpinBox.setObjectName("roll_doubleSpinBox")
        self.gridLayout_4.addWidget(self.roll_doubleSpinBox, 6, 4, 1, 1)
        self.yaw_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.yaw_label.setFont(font)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout_4.addWidget(self.yaw_label, 5, 0, 1, 1)
        self.positionY_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionY_doubleSpinBox.setFont(font)
        self.positionY_doubleSpinBox.setMinimum(-1000000000.0)
        self.positionY_doubleSpinBox.setMaximum(1000000000.0)
        self.positionY_doubleSpinBox.setObjectName("positionY_doubleSpinBox")
        self.gridLayout_4.addWidget(self.positionY_doubleSpinBox, 9, 2, 1, 1)
        self.pitch_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pitch_doubleSpinBox.setFont(font)
        self.pitch_doubleSpinBox.setMinimum(-360.0)
        self.pitch_doubleSpinBox.setMaximum(360.0)
        self.pitch_doubleSpinBox.setObjectName("pitch_doubleSpinBox")
        self.gridLayout_4.addWidget(self.pitch_doubleSpinBox, 6, 2, 1, 1)
        self.roll_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.roll_label.setFont(font)
        self.roll_label.setObjectName("roll_label")
        self.gridLayout_4.addWidget(self.roll_label, 5, 4, 1, 1)
        self.positionZ_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionZ_doubleSpinBox.setFont(font)
        self.positionZ_doubleSpinBox.setMinimum(-1000000000.0)
        self.positionZ_doubleSpinBox.setMaximum(1000000000.0)
        self.positionZ_doubleSpinBox.setObjectName("positionZ_doubleSpinBox")
        self.gridLayout_4.addWidget(self.positionZ_doubleSpinBox, 9, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 9, 1, 1, 1)
        self.autoAlign_pushButton = QtGui.QPushButton(self.transformation_groupBox)
        self.autoAlign_pushButton.setObjectName("autoAlign_pushButton")
        self.gridLayout_4.addWidget(self.autoAlign_pushButton, 11, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 6, 1, 1, 1)
        self.positionX_doubleSpinBox = QtGui.QDoubleSpinBox(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionX_doubleSpinBox.setFont(font)
        self.positionX_doubleSpinBox.setMinimum(-1000000000.0)
        self.positionX_doubleSpinBox.setMaximum(1000000000.0)
        self.positionX_doubleSpinBox.setObjectName("positionX_doubleSpinBox")
        self.gridLayout_4.addWidget(self.positionX_doubleSpinBox, 9, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 9, 5, 1, 1)
        self.rotateAxis_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.rotateAxis_label.setFont(font)
        self.rotateAxis_label.setObjectName("rotateAxis_label")
        self.gridLayout_4.addWidget(self.rotateAxis_label, 4, 0, 1, 1)
        self.position_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.position_label.setFont(font)
        self.position_label.setObjectName("position_label")
        self.gridLayout_4.addWidget(self.position_label, 7, 0, 1, 1)
        self.positionZ_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionZ_label.setFont(font)
        self.positionZ_label.setObjectName("positionZ_label")
        self.gridLayout_4.addWidget(self.positionZ_label, 8, 4, 1, 1)
        self.positionY_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionY_label.setFont(font)
        self.positionY_label.setObjectName("positionY_label")
        self.gridLayout_4.addWidget(self.positionY_label, 8, 2, 1, 1)
        self.positionX_label = QtGui.QLabel(self.transformation_groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.positionX_label.setFont(font)
        self.positionX_label.setObjectName("positionX_label")
        self.gridLayout_4.addWidget(self.positionX_label, 8, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 9, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 6, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 6, 3, 1, 1)
        self.rateOfChange_horizontalSlider = QtGui.QSlider(self.transformation_groupBox)
        self.rateOfChange_horizontalSlider.setMinimum(1)
        self.rateOfChange_horizontalSlider.setMaximum(20)
        self.rateOfChange_horizontalSlider.setProperty("value", 10)
        self.rateOfChange_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateOfChange_horizontalSlider.setObjectName("rateOfChange_horizontalSlider")
        self.gridLayout_4.addWidget(self.rateOfChange_horizontalSlider, 10, 2, 1, 1)
        self.rateOfChange_label = QtGui.QLabel(self.transformation_groupBox)
        self.rateOfChange_label.setObjectName("rateOfChange_label")
        self.gridLayout_4.addWidget(self.rateOfChange_label, 10, 0, 1, 1)
        self.dataCloudActive_radioButton = QtGui.QRadioButton(self.transformation_groupBox)
        self.dataCloudActive_radioButton.setObjectName("dataCloudActive_radioButton")
        self.gridLayout_4.addWidget(self.dataCloudActive_radioButton, 2, 0, 1, 1)
        self.imageActive_radioButton = QtGui.QRadioButton(self.transformation_groupBox)
        self.imageActive_radioButton.setEnabled(False)
        self.imageActive_radioButton.setObjectName("imageActive_radioButton")
        self.gridLayout_4.addWidget(self.imageActive_radioButton, 3, 0, 1, 1)
        self.activeModel_label = QtGui.QLabel(self.transformation_groupBox)
        self.activeModel_label.setObjectName("activeModel_label")
        self.gridLayout_4.addWidget(self.activeModel_label, 0, 0, 1, 1)
        self.scaffoldActive_radioButton = QtGui.QRadioButton(self.transformation_groupBox)
        self.scaffoldActive_radioButton.setObjectName("scaffoldActive_radioButton")
        self.gridLayout_4.addWidget(self.scaffoldActive_radioButton, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.transformation_groupBox)
        self.nodeCreator_groupBox = QtGui.QGroupBox(self.fitPage)
        self.nodeCreator_groupBox.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.nodeCreator_groupBox.setFont(font)
        self.nodeCreator_groupBox.setObjectName("nodeCreator_groupBox")
        self.gridLayout_7 = QtGui.QGridLayout(self.nodeCreator_groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.createData_checkBox = QtGui.QCheckBox(self.nodeCreator_groupBox)
        self.createData_checkBox.setObjectName("createData_checkBox")
        self.gridLayout_7.addWidget(self.createData_checkBox, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 4, 3, 1, 1)
        self.subGroupName_label = QtGui.QLabel(self.nodeCreator_groupBox)
        self.subGroupName_label.setEnabled(False)
        self.subGroupName_label.setObjectName("subGroupName_label")
        self.gridLayout_7.addWidget(self.subGroupName_label, 6, 1, 1, 1)
        self.evaluate_pushButton = QtGui.QPushButton(self.nodeCreator_groupBox)
        self.evaluate_pushButton.setEnabled(False)
        self.evaluate_pushButton.setObjectName("evaluate_pushButton")
        self.gridLayout_7.addWidget(self.evaluate_pushButton, 8, 1, 1, 1)
        self.destroyNode_pushButton = QtGui.QPushButton(self.nodeCreator_groupBox)
        self.destroyNode_pushButton.setEnabled(False)
        self.destroyNode_pushButton.setObjectName("destroyNode_pushButton")
        self.gridLayout_7.addWidget(self.destroyNode_pushButton, 9, 1, 1, 1)
        self.subGroupName_lineEdit = QtGui.QLineEdit(self.nodeCreator_groupBox)
        self.subGroupName_lineEdit.setEnabled(False)
        self.subGroupName_lineEdit.setObjectName("subGroupName_lineEdit")
        self.gridLayout_7.addWidget(self.subGroupName_lineEdit, 7, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 8, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.nodeCreator_groupBox)
        self.timeSeries_groupBox = QtGui.QGroupBox(self.fitPage)
        self.timeSeries_groupBox.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.timeSeries_groupBox.setFont(font)
        self.timeSeries_groupBox.setObjectName("timeSeries_groupBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.timeSeries_groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.timePoint_label = QtGui.QLabel(self.timeSeries_groupBox)
        self.timePoint_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timePoint_label.sizePolicy().hasHeightForWidth())
        self.timePoint_label.setSizePolicy(sizePolicy)
        self.timePoint_label.setObjectName("timePoint_label")
        self.gridLayout_6.addWidget(self.timePoint_label, 0, 0, 1, 1)
        self.timePoint_spinBox = QtGui.QSpinBox(self.timeSeries_groupBox)
        self.timePoint_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timePoint_spinBox.sizePolicy().hasHeightForWidth())
        self.timePoint_spinBox.setSizePolicy(sizePolicy)
        self.timePoint_spinBox.setMaximum(1000000000)
        self.timePoint_spinBox.setObjectName("timePoint_spinBox")
        self.gridLayout_6.addWidget(self.timePoint_spinBox, 2, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 7, 1, 1, 1)
        self.frameIndex_spinBox = QtGui.QSpinBox(self.timeSeries_groupBox)
        self.frameIndex_spinBox.setObjectName("frameIndex_spinBox")
        self.gridLayout_6.addWidget(self.frameIndex_spinBox, 10, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 2, 1, 1, 1)
        self.play_pushButton = QtGui.QPushButton(self.timeSeries_groupBox)
        self.play_pushButton.setObjectName("play_pushButton")
        self.gridLayout_6.addWidget(self.play_pushButton, 3, 0, 1, 1)
        self.fps_spinBox = QtGui.QSpinBox(self.timeSeries_groupBox)
        self.fps_spinBox.setMinimum(1)
        self.fps_spinBox.setProperty("value", 30)
        self.fps_spinBox.setObjectName("fps_spinBox")
        self.gridLayout_6.addWidget(self.fps_spinBox, 11, 1, 1, 1)
        self.fps_label = QtGui.QLabel(self.timeSeries_groupBox)
        self.fps_label.setObjectName("fps_label")
        self.gridLayout_6.addWidget(self.fps_label, 11, 0, 1, 1)
        self.frameIndex_label = QtGui.QLabel(self.timeSeries_groupBox)
        self.frameIndex_label.setObjectName("frameIndex_label")
        self.gridLayout_6.addWidget(self.frameIndex_label, 10, 0, 1, 1)
        self.loop_checkBox = QtGui.QCheckBox(self.timeSeries_groupBox)
        self.loop_checkBox.setObjectName("loop_checkBox")
        self.gridLayout_6.addWidget(self.loop_checkBox, 8, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.timeSeries_groupBox)
        self.groupBoxProjectData = QtGui.QGroupBox(self.fitPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBoxProjectData.setFont(font)
        self.groupBoxProjectData.setObjectName("groupBoxProjectData")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxProjectData)
        self.gridLayout_5.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.projectPointsButton = QtGui.QPushButton(self.groupBoxProjectData)
        self.projectPointsButton.setObjectName("projectPointsButton")
        self.gridLayout_5.addWidget(self.projectPointsButton, 0, 0, 1, 1)
        self.projectClearButton = QtGui.QPushButton(self.groupBoxProjectData)
        self.projectClearButton.setObjectName("projectClearButton")
        self.gridLayout_5.addWidget(self.projectClearButton, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxProjectData)
        self.filterDataGroupBox = QtGui.QGroupBox(self.fitPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.filterDataGroupBox.setFont(font)
        self.filterDataGroupBox.setObjectName("filterDataGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.filterDataGroupBox)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.filterNonNormalProjectionLimitLabel = QtGui.QLabel(self.filterDataGroupBox)
        self.filterNonNormalProjectionLimitLabel.setObjectName("filterNonNormalProjectionLimitLabel")
        self.gridLayout_3.addWidget(self.filterNonNormalProjectionLimitLabel, 2, 1, 1, 1)
        self.filterTopErrorProportionLineEdit = QtGui.QLineEdit(self.filterDataGroupBox)
        self.filterTopErrorProportionLineEdit.setObjectName("filterTopErrorProportionLineEdit")
        self.gridLayout_3.addWidget(self.filterTopErrorProportionLineEdit, 0, 2, 1, 1)
        self.filterNonNormalProjectionLimitLineEdit = QtGui.QLineEdit(self.filterDataGroupBox)
        self.filterNonNormalProjectionLimitLineEdit.setObjectName("filterNonNormalProjectionLimitLineEdit")
        self.gridLayout_3.addWidget(self.filterNonNormalProjectionLimitLineEdit, 2, 2, 1, 1)
        self.filterTopErrorProportionLabel = QtGui.QLabel(self.filterDataGroupBox)
        self.filterTopErrorProportionLabel.setObjectName("filterTopErrorProportionLabel")
        self.gridLayout_3.addWidget(self.filterTopErrorProportionLabel, 0, 1, 1, 1)
        self.filterTopErrorPushButton = QtGui.QPushButton(self.filterDataGroupBox)
        self.filterTopErrorPushButton.setObjectName("filterTopErrorPushButton")
        self.gridLayout_3.addWidget(self.filterTopErrorPushButton, 0, 0, 1, 1)
        self.filterNonNormalPushButton = QtGui.QPushButton(self.filterDataGroupBox)
        self.filterNonNormalPushButton.setObjectName("filterNonNormalPushButton")
        self.gridLayout_3.addWidget(self.filterNonNormalPushButton, 2, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.filterDataGroupBox)
        self.fitSettingsGroupBox = QtGui.QGroupBox(self.fitPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.fitSettingsGroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.fitSettingsGroupBox.setFont(font)
        self.fitSettingsGroupBox.setObjectName("fitSettingsGroupBox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.fitSettingsGroupBox)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fitSettingsLoadSaveWidgets = QtGui.QWidget(self.fitSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitSettingsLoadSaveWidgets.sizePolicy().hasHeightForWidth())
        self.fitSettingsLoadSaveWidgets.setSizePolicy(sizePolicy)
        self.fitSettingsLoadSaveWidgets.setObjectName("fitSettingsLoadSaveWidgets")
        self.gridLayout_2 = QtGui.QGridLayout(self.fitSettingsLoadSaveWidgets)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fitLoadButton = QtGui.QPushButton(self.fitSettingsLoadSaveWidgets)
        self.fitLoadButton.setEnabled(True)
        self.fitLoadButton.setObjectName("fitLoadButton")
        self.gridLayout_2.addWidget(self.fitLoadButton, 0, 0, 1, 1)
        self.fitSaveButton = QtGui.QPushButton(self.fitSettingsLoadSaveWidgets)
        self.fitSaveButton.setEnabled(True)
        self.fitSaveButton.setObjectName("fitSaveButton")
        self.gridLayout_2.addWidget(self.fitSaveButton, 0, 1, 1, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.verticalLayout_6.addWidget(self.fitSettingsLoadSaveWidgets)
        self.fitSettingsWidget = QtGui.QWidget(self.fitSettingsGroupBox)
        self.fitSettingsWidget.setObjectName("fitSettingsWidget")
        self.formLayout_2 = QtGui.QFormLayout(self.fitSettingsWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 3, 0, 3)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.fitStrainPenaltyLabel = QtGui.QLabel(self.fitSettingsWidget)
        self.fitStrainPenaltyLabel.setObjectName("fitStrainPenaltyLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.fitStrainPenaltyLabel)
        self.fitStrainPenaltyLineEdit = QtGui.QLineEdit(self.fitSettingsWidget)
        self.fitStrainPenaltyLineEdit.setObjectName("fitStrainPenaltyLineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.fitStrainPenaltyLineEdit)
        self.fitMaxIterationsLabel = QtGui.QLabel(self.fitSettingsWidget)
        self.fitMaxIterationsLabel.setObjectName("fitMaxIterationsLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.fitMaxIterationsLabel)
        self.fitMaxIterationsSpinBox = QtGui.QSpinBox(self.fitSettingsWidget)
        self.fitMaxIterationsSpinBox.setMinimum(1)
        self.fitMaxIterationsSpinBox.setMaximum(100)
        self.fitMaxIterationsSpinBox.setProperty("value", 1)
        self.fitMaxIterationsSpinBox.setObjectName("fitMaxIterationsSpinBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.fitMaxIterationsSpinBox)
        self.fitPerformButton = QtGui.QPushButton(self.fitSettingsWidget)
        self.fitPerformButton.setObjectName("fitPerformButton")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.fitPerformButton)
        self.verticalLayout_6.addWidget(self.fitSettingsWidget)
        self.verticalLayout_4.addWidget(self.fitSettingsGroupBox)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.toolBox.addItem(self.fitPage, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.displayOptions_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayOptions_groupBox.sizePolicy().hasHeightForWidth())
        self.displayOptions_groupBox.setSizePolicy(sizePolicy)
        self.displayOptions_groupBox.setObjectName("displayOptions_groupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.displayOptions_groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.displayDataPoints_checkBox = QtGui.QCheckBox(self.displayOptions_groupBox)
        self.displayDataPoints_checkBox.setObjectName("displayDataPoints_checkBox")
        self.verticalLayout_9.addWidget(self.displayDataPoints_checkBox)
        self.displayNodes_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayNodes_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodes_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodes_frame.setObjectName("displayNodes_frame")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.displayNodes_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.displayNodePoints_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        self.displayNodePoints_checkBox.setObjectName("displayNodePoints_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodePoints_checkBox)
        self.displayNodeNumbers_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeNumbers_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeNumbers_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeNumbers_checkBox.setObjectName("displayNodeNumbers_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeNumbers_checkBox)
        self.displayNodeDerivatives_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivatives_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivatives_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivatives_checkBox.setObjectName("displayNodeDerivatives_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeDerivatives_checkBox)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_9.addWidget(self.displayNodes_frame)
        self.displayNodeDerivativeLabels_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayNodeDerivativeLabels_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodeDerivativeLabels_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodeDerivativeLabels_frame.setObjectName("displayNodeDerivativeLabels_frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.displayNodeDerivativeLabels_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.displayNodeDerivativeLabelsD1_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD1_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD1_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD1_checkBox.setObjectName("displayNodeDerivativeLabelsD1_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD1_checkBox)
        self.displayNodeDerivativeLabelsD2_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD2_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD2_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD2_checkBox.setObjectName("displayNodeDerivativeLabelsD2_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD2_checkBox)
        self.displayNodeDerivativeLabelsD3_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD3_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD3_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD3_checkBox.setObjectName("displayNodeDerivativeLabelsD3_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD3_checkBox)
        self.displayNodeDerivativeLabelsD12_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD12_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD12_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD12_checkBox.setObjectName("displayNodeDerivativeLabelsD12_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD12_checkBox)
        self.displayNodeDerivativeLabelsD13_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD13_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD13_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD13_checkBox.setObjectName("displayNodeDerivativeLabelsD13_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD13_checkBox)
        self.displayNodeDerivativeLabelsD23_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD23_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD23_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD23_checkBox.setObjectName("displayNodeDerivativeLabelsD23_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD23_checkBox)
        self.displayNodeDerivativeLabelsD123_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD123_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD123_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD123_checkBox.setObjectName("displayNodeDerivativeLabelsD123_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD123_checkBox)
        self.verticalLayout_9.addWidget(self.displayNodeDerivativeLabels_frame)
        self.displayLines_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayLines_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayLines_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayLines_frame.setObjectName("displayLines_frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.displayLines_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.displayLines_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        self.displayLines_checkBox.setObjectName("displayLines_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLines_checkBox)
        self.displayLinesExterior_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLinesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displayLinesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displayLinesExterior_checkBox.setObjectName("displayLinesExterior_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLinesExterior_checkBox)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_9.addWidget(self.displayLines_frame)
        self.displaySurfaces_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displaySurfaces_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displaySurfaces_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displaySurfaces_frame.setObjectName("displaySurfaces_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.displaySurfaces_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displaySurfaces_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        self.displaySurfaces_checkBox.setObjectName("displaySurfaces_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfaces_checkBox)
        self.displaySurfacesExterior_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesExterior_checkBox.setObjectName("displaySurfacesExterior_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesExterior_checkBox)
        self.displaySurfacesTranslucent_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesTranslucent_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesTranslucent_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesTranslucent_checkBox.setObjectName("displaySurfacesTranslucent_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesTranslucent_checkBox)
        self.displaySurfacesWireframe_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesWireframe_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesWireframe_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesWireframe_checkBox.setObjectName("displaySurfacesWireframe_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesWireframe_checkBox)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.verticalLayout_9.addWidget(self.displaySurfaces_frame)
        self.displayElements_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayElements_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayElements_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayElements_frame.setObjectName("displayElements_frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.displayElements_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.displayElementNumbers_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        self.displayElementNumbers_checkBox.setObjectName("displayElementNumbers_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementNumbers_checkBox)
        self.displayElementAxes_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayElementAxes_checkBox.sizePolicy().hasHeightForWidth())
        self.displayElementAxes_checkBox.setSizePolicy(sizePolicy)
        self.displayElementAxes_checkBox.setObjectName("displayElementAxes_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementAxes_checkBox)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.verticalLayout_9.addWidget(self.displayElements_frame)
        self.displayMisc_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayMisc_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayMisc_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayMisc_frame.setObjectName("displayMisc_frame")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.displayMisc_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.displayAxes_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayAxes_checkBox.setObjectName("displayAxes_checkBox")
        self.horizontalLayout_8.addWidget(self.displayAxes_checkBox)
        self.displayAnnotationPoints_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayAnnotationPoints_checkBox.setObjectName("displayAnnotationPoints_checkBox")
        self.horizontalLayout_8.addWidget(self.displayAnnotationPoints_checkBox)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_9.addWidget(self.displayMisc_frame)
        self.verticalLayout_3.addWidget(self.displayOptions_groupBox)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAllButton = QtGui.QPushButton(self.frame)
        self.viewAllButton.setObjectName("viewAllButton")
        self.horizontalLayout_2.addWidget(self.viewAllButton)
        self.doneButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_2.addWidget(self.doneButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.sceneviewer_widget = BaseSceneviewerWidget(ScaffoldfitterWidget, shared_open_gl_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewerWidget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(ScaffoldfitterWidget)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(ScaffoldfitterWidget)

    def retranslateUi(self, ScaffoldfitterWidget):
        ScaffoldfitterWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Scaffold Finite Element Mesh Fitter", None, QtGui.QApplication.UnicodeUTF8))
        self.transformation_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.pitch_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.yaw_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.roll_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.autoAlign_pushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Auto Centre Align", None, QtGui.QApplication.UnicodeUTF8))
        self.rotateAxis_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Rotation (Euler angles):", None, QtGui.QApplication.UnicodeUTF8))
        self.position_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Postions:", None, QtGui.QApplication.UnicodeUTF8))
        self.positionZ_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.positionY_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.positionX_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.rateOfChange_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Rate of change:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataCloudActive_radioButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Data cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.imageActive_radioButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Image plane / video", None, QtGui.QApplication.UnicodeUTF8))
        self.activeModel_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Active model:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldActive_radioButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Scaffold", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeCreator_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Manual Data Node Creator (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.createData_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Create data node", None, QtGui.QApplication.UnicodeUTF8))
        self.subGroupName_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Subgroup name:", None, QtGui.QApplication.UnicodeUTF8))
        self.evaluate_pushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Evaluate Data Node On Scaffold", None, QtGui.QApplication.UnicodeUTF8))
        self.destroyNode_pushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Destroy Selected Data Node", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSeries_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Time (active only if time-series/video data is available)", None, QtGui.QApplication.UnicodeUTF8))
        self.timePoint_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Time value:", None, QtGui.QApplication.UnicodeUTF8))
        self.play_pushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.fps_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "FPS:", None, QtGui.QApplication.UnicodeUTF8))
        self.frameIndex_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Frame index:", None, QtGui.QApplication.UnicodeUTF8))
        self.loop_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Lopp", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxProjectData.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Projections", None, QtGui.QApplication.UnicodeUTF8))
        self.projectPointsButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Project or re-project all active points to the nearest locations on the model surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.projectPointsButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Project Points", None, QtGui.QApplication.UnicodeUTF8))
        self.projectClearButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Clear all projections and reset the active data points to include all", None, QtGui.QApplication.UnicodeUTF8))
        self.projectClearButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDataGroupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Filter Data", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalProjectionLimitLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Proj. Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorProportionLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Proportion of maximum error (0.0 to 1.0) used to filter data points", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalProjectionLimitLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Minimum dot product for removing non-normal projections (<=1.0 where 1.0 is perfecly normal)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorProportionLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Proportion:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorPushButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove data points with errors greater than the given proportion of the maximum error", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorPushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove top error", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalPushButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove data points with projections whose dot product with the surface normal is less than the given limit (1.0 is perface alignment, 0.0 is orthogonal)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalPushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove non-normal", None, QtGui.QApplication.UnicodeUTF8))
        self.fitSettingsGroupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.fitLoadButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Load pre-saved fitting settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fitLoadButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fitSaveButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Save fit settings for recall later or when next run", None, QtGui.QApplication.UnicodeUTF8))
        self.fitSaveButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fitStrainPenaltyLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Strain Penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitStrainPenaltyLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Penalty factor for strains, typically << 1.0 e.g. 0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.fitMaxIterationsLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Max. Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitMaxIterationsSpinBox.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Maximum number of iterations to limit fit time if convergence is slow", None, QtGui.QApplication.UnicodeUTF8))
        self.fitPerformButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Perform fitting up to at most the set number of iteratations", None, QtGui.QApplication.UnicodeUTF8))
        self.fitPerformButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Perform Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.fitPage), QtGui.QApplication.translate("ScaffoldfitterWidget", "Fitting Options", None, QtGui.QApplication.UnicodeUTF8))
        self.displayOptions_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Display options:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataPoints_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Data points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodePoints_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Node points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeNumbers_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Node numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivatives_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Node derivatives", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD1_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD2_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D2", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD3_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D3", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD12_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D12", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD13_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D13", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD23_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D23", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD123_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D123", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLines_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLinesExterior_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfaces_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesExterior_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesTranslucent_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Transluc.", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesWireframe_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementNumbers_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Element numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementAxes_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Element axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAxes_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAnnotationPoints_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Annotation points", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Adjust the view to see the whole model", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Finish this step", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
